### ISSUE TITLE
pFsense version 2.5.2 boot loop and crash on virtual box

### ISSUE THREAD

**Issue by P0tterShell** [codefellows/seattle-ops-301d3#1]
pFsense version 2.5.2 boot loop and crash on virtual box, fix is to run an older version of pFsense

https://docs.netgate.com/pfsense/en/latest/releases/versions.html

Students will use 2.5.1 in ops-401d3 to see if the issue persists.

**Comment by brookr** [comment]
Tracking this in the guide repo: https://github.com/codefellows/ops-301-guide/issues/87
