### ISSUE TITLE
Bad link for slide template in project guidelines

### ISSUE THREAD

**Issue by P0tterShell** [codefellows/seattle-ops-301d3#2]
link should be updated to https://docs.google.com/presentation/d/1NeXKKEpjK2DDme8EwlZBsJndUqIgGYzWrY6FAYtNTf0/edit?usp=sharing

**Comment by brookr** [comment]
Link appears correct in the Guide Repo: https://github.com/codefellows/ops-301-guide/blob/main/curriculum/class-15/project-guidelines.md

I'm unclear how this repo got the wrong link, unless it was updated after this repo was cloned. 

Regardless: Fixed here in this repo now. 

Thanks for creating the issue!
